/**
 * Shared constants and threat classifications for Cyber Safety Platform.
 * 
 * IMPORTANT SECURITY PRINCIPLE:
 * We do NOT mathematically guarantee 100% security or vulnerability.
 * Classification levels reflect evidence-based confidence levels.
 */

const THREAT_LEVELS = Object.freeze({
  SAFE: 'SAFE',
  SUSPICIOUS: 'SUSPICIOUS',
  HIGH_CONFIDENCE_THREAT: 'HIGH_CONFIDENCE_THREAT',
  UNKNOWN: 'UNKNOWN'
});

const RISK_LEVELS = Object.freeze({
  NONE: 'NONE',
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH'
});

const SIGNAL_SEVERITY = Object.freeze({
  INFO: 'INFO',
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
});

const REPORT_STATUS = Object.freeze({
  PENDING: 'PENDING',
  REVIEWED: 'REVIEWED',
  ACTIONED: 'ACTIONED',
  REJECTED: 'REJECTED'
});

const EVIDENCE_TYPES = Object.freeze({
  TEXT_DESCRIPTION: 'TEXT_DESCRIPTION',
  URL_REFERENCE: 'URL_REFERENCE',
  SECURITY_ADVISORY: 'SECURITY_ADVISORY'
});

const EVIDENCE_SOURCES = Object.freeze({
  WIKIPEDIA: 'WIKIPEDIA',
  REDDIT: 'REDDIT',
  GOOGLE_WEB_RISK: 'GOOGLE_WEB_RISK',
  COMMUNITY_REPORT: 'COMMUNITY_REPORT',
  LOCAL_DATABASE: 'LOCAL_DATABASE'
});

const EVIDENCE_SOURCE_TYPES = Object.freeze({
  SECURITY_INTELLIGENCE: 'SECURITY_INTELLIGENCE',
  COMMUNITY_DISCUSSION: 'COMMUNITY_DISCUSSION',
  PUBLIC_KNOWLEDGE: 'PUBLIC_KNOWLEDGE',
  USER_REPORT: 'USER_REPORT'
});

const VERIFICATION_STATUS = Object.freeze({
  VERIFIED: 'VERIFIED',
  SUPPORTED: 'SUPPORTED',
  UNVERIFIED: 'UNVERIFIED',
  SYSTEM_DETECTED: 'SYSTEM_DETECTED',
  PENDING: 'PENDING'
});

const RELEVANCE_LEVELS = Object.freeze({
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
  NONE: 'NONE'
});

module.exports = {
  THREAT_LEVELS,
  RISK_LEVELS,
  SIGNAL_SEVERITY,
  REPORT_STATUS,
  EVIDENCE_TYPES,
  EVIDENCE_SOURCES,
  EVIDENCE_SOURCE_TYPES,
  VERIFICATION_STATUS,
  RELEVANCE_LEVELS
};
